### ISSUE TITLE
please add sing-box

### ISSUE THREAD

**Issue by alighaffari3000** [Soroushnk/Astro#10]
سلام. اگه قابلیت نصب هسته سینگ باکس و همچنین ساخت کانفیگ با پروتکل های مختلف باهاش رو به اسکریپت اضافه کنید خیلی خوب میشه.

**Comment by alighaffari3000** [comment]
دمت گرم. ممنون از زحماتت.
این دو تا اسکریپت های خوبی هستند. دومی امکان مدیریت کاربران هم داره.
https://github.com/namelesghoul/sing-box-REALITY

https://github.com/aleskxyz/reality-ezpz

**Comment by mfat** [comment]
https://github.com/aleskxyz/reality-ezpz 
این از همشون بهتره
