### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by FaridSalah** [Soroushnk/Astro#16]
How to uninstall WordPress?

**Comment by Soroushnk** [comment]
you can use command below
`sudo a2dissite wordpress
sudo rm /etc/apache2/sites-available/wordpress.conf
sudo systemctl restart apache2`
then run the command below
`sudo rm -rf /srv/www/wordpress`

and for last one run the command below to uninstall sql

`echo "DROP DATABASE wordpress;" | sudo mysql -u root -p
echo "DROP USER wordpress@localhost;" | sudo mysql -u root -p`

**Comment by FaridSalah** [comment]
I successfully uninstalled WordPress. But, the RAM usage continues.

After installing WP, approximately 600MB of RAM got involved.

**Comment by Soroushnk** [comment]
You can use comman below to see memory usage
 ```
top -o %MEM
```
