### ISSUE TITLE
مشکل در سیسکو

### ISSUE THREAD

**Issue by sinath72** [Soroushnk/Astro#18]
سلام 
من بعد از نصب سیسکو وقتی بهش وصل میشم هیچ سایتی رو بالا نمیاره
مشکل از چیه؟

**Comment by sinath72** [comment]
لاگ من : 11/05/1402
     10:25:03 ب.ظ    Contacting xxxx.
     10:25:22 ب.ظ    User credentials entered.
     10:25:27 ب.ظ    User credentials entered.
     10:25:38 ب.ظ    User credentials entered.
     10:25:47 ب.ظ    User credentials entered.
     10:25:48 ب.ظ    Connection attempt has failed.
     10:25:53 ب.ظ    User credentials entered.
     10:25:59 ب.ظ    User credentials entered.
     10:26:00 ب.ظ    Establishing VPN session...
     10:26:03 ب.ظ    The AnyConnect Downloader is performing update checks...
     10:26:03 ب.ظ    Checking for profile updates...
     10:26:03 ب.ظ    Checking for product updates...
     10:26:08 ب.ظ    Checking for customization updates...
     10:26:09 ب.ظ    Performing any required updates...
     10:26:09 ب.ظ    The AnyConnect Downloader updates have been completed.
     10:26:09 ب.ظ    Establishing VPN - Initiating connection...
     10:26:09 ب.ظ    Establishing VPN session...
     10:26:10 ب.ظ    Establishing VPN - Examining system...
     10:26:10 ب.ظ    Establishing VPN - Activating VPN adapter...
     10:26:17 ب.ظ    Establishing VPN - Configuring system...
     10:26:17 ب.ظ    Establishing VPN...
     10:26:17 ب.ظ    Connected to xxxx.

**Comment by Soroushnk** [comment]
The connection seems okay does it disconnect  after several minutes  or not if yes . It means th dtks is closed by the government  and thats the issue

**Comment by sinath72** [comment]
not disconnect after 10 minutes i tested and i tested this protocol on my Germany VPS  and have same result

![Screenshot (77)](https://github.com/Soroushnk/Astro/assets/56226543/77bead66-bb43-4d94-b0c2-93c793bfa56b)

**Comment by Soroushnk** [comment]
Government  has closed  oscerv on some ISP's . That might be youre problem . If its connect it may have problem with your system configuration

**Comment by sinath72** [comment]
i tested on ios & pc in iran and mac vps in germany all of this connected but can not browse internet and i immediately i connect to cisco vpn server my internet connection loss and when i disconnected return my internet connection

what to do for fixed this?

**Comment by Soroushnk** [comment]
Try using tunnel . It may fix youre problem
