### ISSUE TITLE
مشکل قعط شدن اینترنت سرور

### ISSUE THREAD

**Issue by rezak222** [Soroushnk/Astro#19]
سلام . من از طریق اسکریپت شما برای حل مشکل ارور 403 و کپچا استفاده کردم . اول مراحل نصب رو طبق یک ویدیو جلو رفتم و کار نکرد و بعد در قسمت آخر که یک سئوال میپرسه که اولیش به ipv6 ربط داره و دومیش به ipv4 گزینه 2 رو زدم و بعد کلا نت سرور قعط شد . از طریق کنسول دسترسی دارم ولی سرور نه پینگ داره و نه از داخل کنسول از جایی پینگ میگیره . لطفا راهنمایی کنید چجوری مشکل رو حل کنم . اطلاعات مهمه و نمیتونم سیستم عامل رو مجدد نصب کنم

**Comment by Soroushnk** [comment]
از همون اسکریپت گرینه 14 رو امتحان کنین warp پاک میشه

**Comment by rezak222** [comment]
سرور نتش قعطه ، نمیتونم اسکریپت رو اجرا کنم

**Comment by Soroushnk** [comment]
دستورات زیر رو به ترتیب وارد کنین 
`warp-cli disable-always-on`
`warp-cli disconnect`
`systemctl stop warp-svc`
`rm -f /etc/apt/sources.list.d/cloudflare-client.list`

**Comment by rezak222** [comment]
![0](https://github.com/Soroushnk/Astro/assets/126603005/7a840879-87c5-4cb0-b10e-4610432966c0)
این ارور ها رو داد
