### ISSUE TITLE
تونل کردن دو سرور بهم

### ISSUE THREAD

**Issue by aliraza7926** [Soroushnk/Astro#20]
بخش تونل کردن دو سرور بهم درست نمایش داده نمیشه
و همینطور توی قسمتی که پورت اس اس اچ  رو نیاز داره پورت سرور ایران باید وارد بشه یا خارج؟

**Comment by Soroushnk** [comment]
وقت بخیر نمایش اصلاح شد و بورت ssh هم باید مال ایران رو بزنید

**Comment by aliraza7926** [comment]
ممنونم
