### ISSUE TITLE
مشکل در نصب سیسکو

### ISSUE THREAD

**Issue by H2mz** [Soroushnk/Astro#21]
سلام

وقتی میزنم سیسکو نصب بشه مراحل میره ولی عملا سیسکو اصلا نصب نمیشه

**Comment by Soroushnk** [comment]
نوع سیستم عامل شما چیه ؟
بسته به اون توی /etc/oscerv  اگر وجود داشته باشه  نصب شده همچنین یه برنامه به همین اسم در حال اجرا باید باشه (oscerv)

**Comment by H2mz** [comment]
تشکر حل شد

**Comment by H2mz** [comment]
امکان محدودیت حجم و زمان داره این اسکریت برای سیسکو؟
