### ISSUE TITLE
پنل مرزبان

### ISSUE THREAD

**Issue by Abolfazl123** [Soroushnk/Astro#22]
سلام وقتتون بخیر ممنون بابت اسکریپت خوبتون . یک سوال چرا پنل مرزبان در اسکریپت نیست؟

**Comment by Soroushnk** [comment]
سلام لطف کنید لینک بنل مد نظرتون رو برای ما بفرستید

**Comment by Soroushnk** [comment]
ما اسم پنل مرزبان رو اصلاح کردیم الان در قسمت نصب میتونید مشاهده کنید
