### ISSUE TITLE
استفاده از پنل   مهندس ثنایی که کامل ترین پنل موجود است

### ISSUE THREAD

**Issue by moh3nat** [Soroushnk/Astro#26]
وقت بخیر مهندس سروش 
با توجه به اسکریپت خوبتون توصیه میکنم از پنل
3x-ui 
که بسیار آپشنال و به جرات قوی ترین پنل x-ray  موجود در سبک خودش هست استفاده کنید لطفا لینک صفحه گیتهاب رو پایین قرار میدم 
با تشکر از زحمات شما
https://github.com/MHSanaei/3x-ui/blob/main/x-ui.sh

**Comment by Soroushnk** [comment]
in panel hast dar script
