### ISSUE TITLE
نصب پنل x-ui

### ISSUE THREAD

**Issue by HamidOffline** [Soroushnk/Astro#3]
سلام مرسی بابت این اسکریپت محشترتون
خواستم بدونم چرا وقتی نصب پنل میزنم پنل هایدیفای نصب میشه فقط پنل xui نصب نمیشه؟؟؟

**Comment by Soroushnk** [comment]
هیدیفای یه پنل x-ui نیست  بزرگتره صبر کنید نصب تموم شه یه لینک بهتون میده  با اون لینک وارد پنل بشین
