### ISSUE TITLE
google recapta fix

### ISSUE THREAD

**Issue by hamidtb** [Soroushnk/Astro#4]
hello
can you tell how to use google recapta fix; i contain many option and  chines language and i cant understand how to use it

**Comment by Soroushnk** [comment]
yep sure . if youre server has IPV6 input variables below  inorder after opeing the Astro :
7 
12
y
y
1

**Comment by sinafekri** [comment]
Hello , is it work for ChatGPT?

**Comment by Soroushnk** [comment]
Yep

**Comment by rezak222** [comment]
> yep sure . if youre server has IPV6 input variables below inorder after opeing the Astro : 7 12 y y 1

من تو مرحله آخر 2 زدم و نت سرور پرید . چیکار میشه کرد ؟؟
