### ISSUE TITLE
Easy vless/trojan/naive proxy deploy

### ISSUE THREAD

**Issue by mfat** [Soroushnk/Astro#6]
For users that don't need a panel there are these one-line commands:

https://github.com/SonyaCore/V2RayGen

https://github.com/SonyaCore/Naive-deploy

**Comment by Soroushnk** [comment]
Do you want it to be added to script ?

**Comment by mfat** [comment]
Well these are kind of old now. I will find newer ones and send to you. Thanks.

**Comment by mfat** [comment]
This is the best one right now. It even has a text-based menu for configuration. 

https://github.com/aleskxyz/reality-ezpz
