### ISSUE TITLE
Reality protocol

### ISSUE THREAD

**Issue by techjoyment** [Soroushnk/Astro#7]
با سلام
گزینه Reality Protocol رو وقتی نصب میزنیم در نهایت برمیگرده به منو و مشخصات رو نمیده. نحوه استفاده نامشخص هست.

**Comment by Soroushnk** [comment]
صبر کنید تا کد دوباره چک بشه. اگه ایرادی بود رفع میکنیم

**Comment by alighaffari3000** [comment]
واسه منم همینطوره. کارش که انجام میشه برای چند صدم ثانیه مشخصات میاد و سریع خارج میشه و به منوی اصلی برمیگرده.
